name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    - name: Push to Docker Hub
      use: docker/build-push-action@v1
      with:
        username: ${{ secrects.DOCKER_USERNAME }}
        password: ${{ secrects.DOCKER_PASSWORD }}
        repository: jhn63/app
